# ~/.config/home-manager/tmux.conf

set -as terminal-features ",*:RGB"
set -as terminal-features ",*:Styling"
set -as terminal-overrides ",*:Tc"
set -g default-command "bash"

# Smart toggle for Jujutsu watcher
# If a pane in this window is running 'entr', kill it. Otherwise, open it.
bind-key j run-shell "tmux-jj"

# Copy Mode (Vi style)
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -sel clip -i"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -sel clip -i"

# Neovim navigation integration
is_vim="ps -t '#{pane_tty}' | grep -iq nvim"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

# Splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Window configurations
set -g status-left-length 40
set -g status-right-length 80
set -g status-justify left
set -g renumber-windows on
setw -g monitor-activity on
set -g visual-activity off
