# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/hardware/network/broadcom-43xx.nix")
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/27ee0bdc-2c23-4da3-8e2a-1d185358fe8a";
    fsType = "btrfs";
    options = ["subvol=@root" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/27ee0bdc-2c23-4da3-8e2a-1d185358fe8a";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/27ee0bdc-2c23-4da3-8e2a-1d185358fe8a";
    fsType = "btrfs";
    options = ["subvol=@nix" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/home/pme/Games" = {
    device = "/dev/disk/by-uuid/27ee0bdc-2c23-4da3-8e2a-1d185358fe8a";
    fsType = "btrfs";
    options = ["subvol=@games" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BDCA-A087";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/b7fca11d-3133-4828-a149-09c4b6f1dc0b";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
